# documentation: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
#
name: Deploy NCC course material website
on:
  push:
    branches:
      - main
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Read Python version
        id: pyversion
        run: echo "PYTHON_VERSION=$(cat .python)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
          properdocs --version
      - name: build ULHPC documentation
        run: properdocs build --strict && properdocs gh-deploy --force
